# Send debug messages
debug: false
doMobSpawns: false
minChunkSpawnRad: 3
maxChunkSpawnRad: 6
maxCommandSpawns: 50
spawnTaskDelay: 100
creatureTypeCaps:
  CREATURE: 20
  MONSTER: 20
  WATER_CREATURE: 5
  MISC: 5
  AMBIENT: 0
playerGroupRadius: 128.0
